JORDTUNING = {}

function Tune(overrides)
    if overrides == nil then
        overrides = {}
    end

    JORDTUNING =
    {
		-- Jordan
		JORDAN_HEALTH = 80,
		JORDAN_HUNGER = 200,
		JORDAN_SANITY = 125,
		
		JORDAN_HUNGER_DAY_MULT = 0.35,
		JORDAN_HUNGER_DUSK_MULT = 0.35,
		JORDAN_HUNGER_NIGHT_MULT = 0.7,
		JORDAN_HUNGER_TEMP_MAXMULT = 0.06,
		JORDAN_HUNGER_GROGGY_FLOOR = 0.30,
		JORDAN_HUNGER_GROGGY_CEIL = 0.35,
		
		JORDAN_SANITY_KARMA_DRAIN = 1/60,
		JORDAN_SANITY_NOFOOD_THRESHOLD = 0.3,
		
		JORDAN_DAMAGE_MULT = 0.8,
		
		JORDAN_SPEED_DAY_MULT = 1.50,
		JORDAN_SPEED_DUSK_MULT = 1.25,
		JORDAN_SPEED_NIGHT_MULT = 1,
		JORDAN_SPEED_GROGGY_MULT = 0.75,
		
		JORDAN_TOOLS_AXE_MULT = 1.5,
		JORDAN_TOOLS_PICKAXE_MULT = 1.5,
		JORDAN_TOOLS_AXEPICKAXE_MULT = 2,
		JORDAN_TOOLS_FISHINGROD_MULT = 2/3,
		
		JORDAN_INSULATION = 60,
		JORDAN_SUMMER_INSULATION = 30,
		
		JORDAN_DRYING_MULT_BONUS = 0.2,
		JORDAN_PUDDLE_WETNESS_RATE = 2,
		JORDAN_PUDDLE_WETNESS_THRESHOLD = 50,
		JORDAN_PUDDLE_COOLDOWN = 15,
		JORDAN_DURABILITY_PER_ICE = 2.5,
		
		JORDAN_HEAT_THRESHOLD = 35,
        JORDAN_HEAT_ATTACK_BOOST = 0.008,
		JORDAN_HEAT_ABSORPTION_PENALTY = 0.005,
    }
end

Tune()
