KENTUNING = {}

function Tune(overrides)
    if overrides == nil then
        overrides = {}
    end

    KENTUNING =
    {
		-- MOVED TO MODMAIN.LUA
        --KENDOV_HEALTH = 100,
		--KENDOV_HUNGER = 150,
		--KENDOV_SANITY = 100,
		
		KENDOV_HUNGER_BASEMULT = 1,
		KENDOV_HUNGER_MAXMULT = 1.5,
		KENDOV_HUNGER_FULLMOON_ADDBLOODHEAL = 1,
		
		KENDOV_SANITY_MULT = 0.75,
		KENDOV_SANITY_NIGHT_MULT = 0,
		KENDOV_SANITY_DAY_DRAIN = (1/12)*0.75, -- 75% of vanilla night drain
		
		KENDOV_DAMAGE_DAY_MULT = 0.75,
		KENDOV_DAMAGE_DUSK_MULT = 1.0,
		KENDOV_DAMAGE_NIGHT_MULT = 1.125,
		KENDOV_DAMAGE_CAVE_MULT = 1.0,
		KENDOV_DAMAGE_MAXHEALTH_DAMAGE = 0.125,
		KENDOV_DAMAGE_BLOODBUFF_DAMAGE = 0.25,
		KENDOV_DAMAGE_BLOODBUFF_DURATION = 30, -- One clock segment
		
		KENDOV_FIRE_DAMAGE_SCALE = 1.25,
		KENDOV_FREEZE_RESIST = 5, -- Default 4

		KENDOV_SPEED_DAY_MULT = 0.75,
		KENDOV_SPEED_DAY_SHADE_MULT = 0.9,
		KENDOV_SPEED_DUSK_MULT = 1.125,
		KENDOV_SPEED_NIGHT_MULT = 1.25,
		KENDOV_SPEED_CAVE_MULT = 1.125,
		
		KENDOV_HUMANBLOOD_BOOST = 10,
		
		KENDOV_LIFESTEAL_PERCENT = 0.0125,
		KENDOV_LIFESTEAL_BOOSTER_MULT = 0.5,
		KENDOV_LIFESTEAL_DAY_MULT = 0,
		KENDOV_LIFESTEAL_DUSK_MULT = 1,
		KENDOV_LIFESTEAL_NIGHT_MULT = 2,
		KENDOV_LIFESTEAL_CAVE_MULT = 1,
		KENDOV_LIFESTEAL_FULLMOON_MULT = 4,
		KENDOV_LIFESTEAL_SANITY_MAXMULT = 2,
		
		KENDOV_DARKVISION_SANITY_THRESHOLD = 0.5,
    }
end

Tune()
